documents: graphql/queries/**/*.ts
schema: ../graphql/schema/schema.docs.graphql
hooks:
  afterOneFileWrite:
    - prettier --write
extensions:
  codegen:
    generates:
      graphql/queries/types.generated.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-msw
          - typescript-react-query
        config:
          maybeValue: T | undefined
          enumsAsTypes: true
          noNamespaces: true
          preResolveTypes: true
          onlyOperationTypes: true
          skipTypename: true
          scalars:
            Set: string[]
            Time: string
            Country: string
            Currency: string
            Date: string
            DateTime: string
            Json: 'string | string[] | { [key: string]: any } | { [key: string]: any }[]'
            KeyReferenceInput: string
            Locale: string
            SearchFilter: string
            SearchSort: string
            YearMonth: string
            BigDecimal: string
            Long: string
          fetcher: graphql-request
          exposeQueryKeys: true
          exposeFetcher: true
